name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 22
          script: |
            cd projet10_appli
            git pull origin master
            source venv/bin/activate
            pip install -r requirements.txt
            pkill gunicorn || true
            nohup gunicorn --bind 0.0.0.0:8010 wsgi:app > log.txt 2>&1 &
